/**
 * Archive Service
 * ===============
 * WHY:  Users need to save tab groups for long-term storage with optional encryption.
 * WHAT: CRUD operations for archives - create, restore, list, delete, update metadata.
 * HOW:  Uses chrome.storage.local via ArchiveStorageService, encrypts with CryptoService.
 * NOT:  Does not handle UI, search indexing, or password policy (see related services).
 */

import { ArchivedGroup, ArchiveMetadata, PasswordProtection } from '../types/archive';
import { TabGroup } from '../types/models';
import { ArchiveStorageService } from '../utils/archive-storage';
import { PasswordManager, PasswordSetupResult } from '../utils/password-manager';
import { CryptoService } from '../utils/crypto-service';
import { ArchiveValidator } from '../utils/archive-validator';
import { ArchiveErrorHandler } from '../utils/archive-error-handler';

export interface ArchiveCreationOptions {
  groupId: string;
  reason?: string;
  password?: string;
  passwordHint?: string;
  includeInactiveOnly?: boolean;
}

export interface ArchiveCreationResult {
  success: boolean;
  archiveId?: string;
  error?: string;
  warnings?: string[];
}

export interface ArchiveRestoreOptions {
  archiveId: string;
  password?: string;
  targetWindowId?: number;
  removeAfterRestore?: boolean;
}

export interface ArchiveRestoreResult {
  success: boolean;
  restoredGroup?: TabGroup;
  error?: string;
  tabsRestored?: number;
}

export interface ArchiveListOptions {
  sortBy?: 'date' | 'name' | 'size' | 'accessCount';
  sortOrder?: 'asc' | 'desc';
  includeProtected?: boolean;
  searchQuery?: string;
  dateRange?: {
    start: number;
    end: number;
  };
}

export class ArchiveService {
  /**
   * Create an archive from an existing tab group
   */
  static async createArchive(
    group: TabGroup,
    options: ArchiveCreationOptions
  ): Promise<ArchiveCreationResult> {
    const context = {
      operation: 'createArchive',
      archiveId: group.id,
      metadata: { groupName: group.name, tabCount: group.tabs.length }
    };

    try {
      const warnings: string[] = [];
      let archiveData: TabGroup | string = group;
      let protection: PasswordProtection = {
        passwordProtected: false,
        keyDerivationParams: {
          iterations: 100000,
          algorithm: 'PBKDF2'
        }
      };

      // Validate the input group
      const groupValidation = ArchiveValidator.validateTabGroup(group);
      if (!groupValidation.isValid) {
        const errorDetails = groupValidation.errors.map(e => e.message).join('; ');
        const archiveError = ArchiveErrorHandler.handleError(
          new Error(`Invalid group data: ${errorDetails}`),
          context,
          'ArchiveService'
        );
        return {
          success: false,
          error: archiveError.userMessage || archiveError.message
        };
      }

      // Add validation warnings to results
      if (groupValidation.warnings.length > 0) {
        warnings.push(...groupValidation.warnings.map(w => w.message));
      }

      // Set up password protection if requested
      if (options.password) {
        const passwordSetup = await PasswordManager.setupPasswordProtection(
          group,
          options.password,
          options.passwordHint
        );

        if (!passwordSetup.success || !passwordSetup.protection || !passwordSetup.encryptedData) {
          return {
            success: false,
            error: passwordSetup.error || 'Failed to set up password protection. Please check your password and try again.'
          };
        }

        archiveData = passwordSetup.encryptedData;
        protection = passwordSetup.protection;
      }

      // Create archive metadata
      const metadata: ArchiveMetadata = {
        archivedDate: Date.now(),
        archiveReason: options.reason,
        accessCount: 0,
        restoredCount: 0
      };

      // Create the archived group (checksum will be generated by storage service after sanitization)
      const archive: ArchivedGroup = {
        id: group.id,
        originalGroup: archiveData,
        metadata,
        protection,
        version: '1.0.0'
        // checksum will be generated by storage service after sanitization
      };

      // Store the archive
      const storeResult = await ArchiveStorageService.storeArchive(archive);
      if (!storeResult.success) {
        return {
          success: false,
          error: storeResult.error
        };
      }

      return {
        success: true,
        archiveId: archive.id,
        warnings: warnings.length > 0 ? warnings : undefined
      };

    } catch (error) {
      // DETAILED ERROR LOGGING
      console.error('=== ARCHIVE CREATE ERROR ===');
      console.error('Error object:', error);
      console.error('Error message:', error instanceof Error ? error.message : String(error));
      console.error('Error stack:', error instanceof Error ? error.stack : 'no stack');
      console.error('Context:', context);
      console.error('=== END ERROR ===');

      const archiveError = ArchiveErrorHandler.handleError(
        error instanceof Error ? error : new Error(String(error)),
        context,
        'ArchiveService'
      );
      return {
        success: false,
        error: archiveError.userMessage || archiveError.message
      };
    }
  }

  /**
   * Restore an archived group
   */
  static async restoreArchive(
    options: ArchiveRestoreOptions
  ): Promise<ArchiveRestoreResult> {
    const context = {
      operation: 'restoreArchive',
      archiveId: options.archiveId
    };

    try {
      // Get the archive
      const archive = await ArchiveStorageService.getArchive(options.archiveId);
      if (!archive) {
        const archiveError = ArchiveErrorHandler.handleError(
          new Error('Archive not found'),
          context,
          'ArchiveService'
        );
        return {
          success: false,
          error: archiveError.userMessage || archiveError.message
        };
      }

      let restoredGroup: TabGroup;

      // Handle password-protected archives
      if (archive.protection.passwordProtected) {
        if (!options.password) {
          return {
            success: false,
            error: 'Password required for protected archive'
          };
        }

        const decryptResult = await PasswordManager.verifyPasswordAndDecrypt(
          archive.originalGroup as string,
          options.password,
          archive.protection
        );

        if (!decryptResult.success) {
          const archiveError = ArchiveErrorHandler.handleError(
            new Error(decryptResult.error || 'Decryption failed'),
            context,
            'ArchiveService'
          );
          return {
            success: false,
            error: archiveError.userMessage || archiveError.message
          };
        }

        restoredGroup = decryptResult.data as TabGroup;
      } else {
        restoredGroup = archive.originalGroup as TabGroup;
      }

      // Validate restored data
      const validation = ArchiveValidator.validateTabGroup(restoredGroup);
      if (!validation.isValid) {
        const archiveError = ArchiveErrorHandler.handleError(
          new Error('Archive contains corrupted data'),
          context,
          'ArchiveService'
        );
        return {
          success: false,
          error: archiveError.userMessage || archiveError.message
        };
      }

      // Update restore metadata
      archive.metadata.restoredCount = (archive.metadata.restoredCount || 0) + 1;
      archive.metadata.lastRestored = Date.now();
      await ArchiveStorageService.storeArchive(archive, { overwrite: true });

      // Remove archive if requested
      if (options.removeAfterRestore) {
        await ArchiveStorageService.removeArchive(options.archiveId);
      }

      return {
        success: true,
        restoredGroup,
        tabsRestored: restoredGroup.tabs.length
      };

    } catch (error) {
      const archiveError = ArchiveErrorHandler.handleError(
        error instanceof Error ? error : new Error(String(error)),
        context,
        'ArchiveService'
      );
      return {
        success: false,
        error: archiveError.userMessage || archiveError.message
      };
    }
  }

  /**
   * Get list of archives with filtering and sorting
   */
  static async getArchiveList(options: ArchiveListOptions = {}): Promise<ArchivedGroup[]> {
    try {
      const filters = {
        sortBy: options.sortBy || 'date',
        sortOrder: options.sortOrder || 'desc',
        searchQuery: options.searchQuery,
        dateRange: options.dateRange,
        protectionStatus: options.includeProtected === false ? 'unprotected' : 'all'
      };

      return await ArchiveStorageService.searchArchives(filters);
    } catch (error) {
      ArchiveErrorHandler.handleError(
        error instanceof Error ? error : new Error(String(error)),
        { operation: 'getArchiveList' },
        'ArchiveService'
      );
      return [];
    }
  }

  /**
   * Delete an archive permanently
   */
  static async deleteArchive(archiveId: string): Promise<{ success: boolean; error?: string }> {
    const context = { operation: 'deleteArchive', archiveId };

    try {
      if (!archiveId) {
        const archiveError = ArchiveErrorHandler.handleError(
          new Error('Archive ID is required'),
          context,
          'ArchiveService'
        );
        return {
          success: false,
          error: archiveError.userMessage || archiveError.message
        };
      }

      const result = await ArchiveStorageService.removeArchive(archiveId);
      return result;
    } catch (error) {
      const archiveError = ArchiveErrorHandler.handleError(
        error instanceof Error ? error : new Error(String(error)),
        context,
        'ArchiveService'
      );
      return {
        success: false,
        error: archiveError.userMessage || archiveError.message
      };
    }
  }

  /**
   * Get archive statistics
   */
  static async getArchiveStats(): Promise<{
    totalArchives: number;
    protectedArchives: number;
    totalSizeBytes: number;
    oldestArchive?: Date;
    newestArchive?: Date;
    averageAccessCount: number;
  }> {
    try {
      const archives = await ArchiveStorageService.getArchives();
      const archiveList = Object.values(archives.archives);

      if (archiveList.length === 0) {
        return {
          totalArchives: 0,
          protectedArchives: 0,
          totalSizeBytes: 0,
          averageAccessCount: 0
        };
      }

      const protectedCount = archiveList.filter(a => a.protection.passwordProtected).length;
      const dates = archiveList.map(a => a.metadata.archivedDate);
      const totalAccessCount = archiveList.reduce((sum, a) => sum + a.metadata.accessCount, 0);

      return {
        totalArchives: archiveList.length,
        protectedArchives: protectedCount,
        totalSizeBytes: archives.metadata.totalSizeBytes,
        oldestArchive: new Date(Math.min(...dates)),
        newestArchive: new Date(Math.max(...dates)),
        averageAccessCount: Math.round(totalAccessCount / archiveList.length)
      };
    } catch (error) {
      ArchiveErrorHandler.handleError(
        error instanceof Error ? error : new Error(String(error)),
        { operation: 'getArchiveStats' },
        'ArchiveService'
      );
      return {
        totalArchives: 0,
        protectedArchives: 0,
        totalSizeBytes: 0,
        averageAccessCount: 0
      };
    }
  }

  /**
   * Verify archive password and return decrypted data
   */
  static async verifyArchivePassword(
    archiveId: string,
    password: string
  ): Promise<{
    success: boolean;
    decryptedArchive?: ArchivedGroup;
    error?: string;
  }> {
    const context = { operation: 'verifyArchivePassword', archiveId };

    try {
      const archive = await ArchiveStorageService.getArchive(archiveId);
      if (!archive) {
        return {
          success: false,
          error: 'Archive not found'
        };
      }

      if (!archive.protection.passwordProtected) {
        return {
          success: true,
          decryptedArchive: archive
        };
      }

      // Verify password and decrypt
      const decryptResult = await PasswordManager.verifyPasswordAndDecrypt(
        archive.originalGroup as string,
        password,
        archive.protection
      );

      if (!decryptResult.success) {
        return {
          success: false,
          error: 'Incorrect password'
        };
      }

      // Create decrypted archive object
      const decryptedArchive: ArchivedGroup = {
        ...archive,
        originalGroup: decryptResult.data
      };

      // Update access metadata
      archive.metadata.accessCount = (archive.metadata.accessCount || 0) + 1;
      archive.metadata.lastAccessed = Date.now();
      await ArchiveStorageService.storeArchive(archive, { overwrite: true });

      return {
        success: true,
        decryptedArchive
      };
    } catch (error) {
      const archiveError = ArchiveErrorHandler.handleError(
        error instanceof Error ? error : new Error(String(error)),
        context,
        'ArchiveService'
      );
      return {
        success: false,
        error: archiveError.userMessage || archiveError.message
      };
    }
  }

  /**
   * Export archive data for backup or migration
   */
  static async exportArchive(archiveId: string, password?: string): Promise<{
    success: boolean;
    data?: string;
    error?: string;
  }> {
    const context = { operation: 'exportArchive', archiveId };

    try {
      const archive = await ArchiveStorageService.getArchive(archiveId);
      if (!archive) {
        return {
          success: false,
          error: 'Archive not found'
        };
      }

      // For password-protected archives, verify password first
      if (archive.protection.passwordProtected) {
        if (!password) {
          return {
            success: false,
            error: 'Password required for protected archive'
          };
        }

        const verifyResult = await PasswordManager.verifyPasswordAndDecrypt(
          archive.originalGroup as string,
          password,
          archive.protection
        );

        if (!verifyResult.success) {
          return {
            success: false,
            error: 'Invalid password'
          };
        }
      }

      // Create export data
      const exportData = {
        archive,
        exportedAt: Date.now(),
        exportVersion: '1.0.0'
      };

      return {
        success: true,
        data: JSON.stringify(exportData, null, 2)
      };
    } catch (error) {
      const archiveError = ArchiveErrorHandler.handleError(
        error instanceof Error ? error : new Error(String(error)),
        context,
        'ArchiveService'
      );
      return {
        success: false,
        error: archiveError.userMessage || archiveError.message
      };
    }
  }

  // Private helper methods
}
